# Generated by Django 5.2.11 on 2026-02-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='categoty_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.category'),
            preserve_default=False,
        ),
    ]
