# Generated by Django 5.2.11 on 2026-02-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_subcategory_categoty_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='categoty_id',
            new_name='category_id',
        ),
    ]
