# Generated by Django 5.2.11 on 2026-02-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_categoty_id_subcategory_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_id',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='articles.category'),
            preserve_default=False,
        ),
    ]
