# Generated by Django 5.2.11 on 2026-02-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_subcategory_category_id_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.subcategory'),
        ),
    ]
