# Generated by Django 5.2.11 on 2026-02-23 12:48

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_wikiarticle_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticle',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='articles.subcategory'),
        ),
    ]
