# Generated by Django 5.2.11 on 2026-02-23 13:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_wikiarticle_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
