# Generated by Django 5.2.11 on 2026-02-23 15:31

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_blogarticle_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.CreateModel(
            name='ArticleBlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.blogarticle')),
            ],
        ),
    ]
